# Generated by Django 3.1.5 on 2022-12-06 23:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(blank=True, upload_to='')),
                ('name', models.CharField(default='None', max_length=30)),
                ('col1', models.CharField(choices=[('1', 'Choose...'), ('2', 'name'), ('3', 'job'), ('4', 'company'), ('5', 'date'), ('6', 'phone'), ('7', 'address'), ('8', 'city'), ('9', 'country'), ('10', 'email')], default='Choose...', max_length=30)),
                ('col2', models.CharField(choices=[('1', 'Choose...'), ('2', 'name'), ('3', 'job'), ('4', 'company'), ('5', 'date'), ('6', 'phone'), ('7', 'address'), ('8', 'city'), ('9', 'country'), ('10', 'email')], default='Choose...', max_length=30)),
                ('col3', models.CharField(choices=[('1', 'Choose...'), ('2', 'name'), ('3', 'job'), ('4', 'company'), ('5', 'date'), ('6', 'phone'), ('7', 'address'), ('8', 'city'), ('9', 'country'), ('10', 'email')], default='Choose...', max_length=30)),
                ('col4', models.CharField(choices=[('1', 'Choose...'), ('2', 'name'), ('3', 'job'), ('4', 'company'), ('5', 'date'), ('6', 'phone'), ('7', 'address'), ('8', 'city'), ('9', 'country'), ('10', 'email')], default='Choose...', max_length=30)),
                ('col5', models.CharField(choices=[('1', 'Choose...'), ('2', 'name'), ('3', 'job'), ('4', 'company'), ('5', 'date'), ('6', 'phone'), ('7', 'address'), ('8', 'city'), ('9', 'country'), ('10', 'email')], default='Choose...', max_length=30)),
                ('col6', models.CharField(choices=[('1', 'Choose...'), ('2', 'name'), ('3', 'job'), ('4', 'company'), ('5', 'date'), ('6', 'phone'), ('7', 'address'), ('8', 'city'), ('9', 'country'), ('10', 'email')], default='Choose...', max_length=30)),
                ('col7', models.CharField(choices=[('1', 'Choose...'), ('2', 'name'), ('3', 'job'), ('4', 'company'), ('5', 'date'), ('6', 'phone'), ('7', 'address'), ('8', 'city'), ('9', 'country'), ('10', 'email')], default='Choose...', max_length=30)),
                ('name1', models.CharField(blank=True, default='None', max_length=30)),
                ('name2', models.CharField(blank=True, default='None', max_length=30)),
                ('name3', models.CharField(blank=True, default='None', max_length=30)),
                ('name4', models.CharField(blank=True, default='None', max_length=30)),
                ('name5', models.CharField(blank=True, default='None', max_length=30)),
                ('name6', models.CharField(blank=True, default='None', max_length=30)),
                ('name7', models.CharField(blank=True, default='None', max_length=30)),
                ('ord1', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('ord2', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('ord3', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('ord4', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('ord5', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('ord6', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('ord7', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('rows', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
